FROM prefecthq/prefect:2.7.7-python3.9

COPY docker-requirements.txt .

RUN pip install -r docker-requirements.txt --trusted-host pypi.python.org

COPY prefect_etl_docker.py /opt/prefect/flows/
COPY data /opt/prefect/data


